title: Sebastjan Cizel
author: Sebastjan Cizel
email: sebastjancizel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD student in Mathematics at the University of Oxford. My research is focused on special geometric structures
  arising in string theory. 
# social links
twitter_username: scizel1 # DO NOT include the @ character, or else the build will fail!
github_username:  sebastjancizel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: fongandrew/hydeout

theme: jekyll-theme-minimal